esp_toml_version = 1.0
firmware_images_url = "https://espressif.github.io/esp-brookesia/"

supported_apps = ["speaker_0_12_1_dev_echoear_1_0","speaker_0_12_1_dev_echoear_1_2"]

[speaker_0_12_1_dev_echoear_1_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "speaker_0_12_1_dev_echoear_1_0.bin"
ios_app_url = ""
android_app_url = ""

[speaker_0_12_1_dev_echoear_1_2]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "speaker_0_12_1_dev_echoear_1_2.bin"
ios_app_url = ""
android_app_url = ""
