esp_toml_version = 1.0
firmware_images_url = "https://aihwmakers.github.io/echoear-images/"

supported_apps = ["xiaozhi_echoear_v1_8_5","speaker_0_12_1_dev_echoear_1_2"]

[xiaozhi_echoear_v1_8_5]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "xiaozhi_echoear_v1_8_5.bin"
ios_app_url = ""
android_app_url = ""

[speaker_0_12_1_dev_echoear_1_2]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "speaker_0_12_1_dev_echoear_1_2.bin"
ios_app_url = ""
android_app_url = ""
